=== keyanfang/BigVir2084/BigVir2084.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation xml:lang="fr">
            C'est le document de la base de donné du projet BigVir2084.
        </xs:documentation>
    </xs:annotation>

    <xs:element name="BigVir2084" >
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="citoyen" maxOccurs="unbounded"/>
            <xs:element ref="medécin" maxOccurs="unbounded"/>
            <xs:element ref="observatoire" maxOccurs="unbounded"/>
            <xs:element ref="agence" maxOccurs="unbounded"/>
            <xs:element ref="antécédent_medical" maxOccurs="unbounded"/>
            <xs:element ref="historique_social" maxOccurs="unbounded"/>
            <xs:element ref="statut" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:key name="antécédentKey">
        <xs:selector xpath="antécédent_medical"/>
        <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="antécédentKeyRef" refer="antécédentKey">
        <xs:selector xpath="./citoyen/antécédent_medical"/>
        <xs:field xpath="@antécédent_medical"/>
    </xs:keyref>

    <xs:key name="histoireKey">
        <xs:selector xpath="historique_social"/>
        <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="histoireKeyRef" refer="histoireKey">
        <xs:selector xpath="./citoyen/historique_social"/>
        <xs:field xpath="@historique_social"/>
    </xs:keyref>


    <xs:key name="statutKey">
        <xs:selector xpath="statut"/>
        <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="statutKeyRef" refer="statutKey">
        <xs:selector xpath="./citoyen/statut"/>
        <xs:field xpath="@statut"/>
    </xs:keyref>

   <xs:key name="relationKey">
       <xs:selector xpath="./citoyen"/>
       <xs:field xpath="@id" />
   </xs:key>

    <xs:keyref name="relationKeyRef" refer="relationKey">
        <xs:selector xpath="./citoyen/relation_social/personne"/>
        <xs:field xpath="@personne"/>
    </xs:keyref>

    <xs:key name="citoyenKey">
        <xs:selector xpath="./citoyen"/>
        <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="citoyenRef" refer="citoyenKey">
        <xs:selector xpath="./medécin/citoyen"/>
        <xs:field xpath="@citoyen"/>
    </xs:keyref>
  </xs:element>


    <xs:element name="citoyen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="gender" type="xs:string">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="homme|femme"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="age" type="xs:nonNegativeInteger"/>
                <xs:element name="pois" type="xs:decimal"/>
                <xs:element name="antécédent_medical" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="antécédent_medical" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="historique_social" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="historique_social" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="statut" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="statut" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="relation_social" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="personne"  maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="personne" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="visibilité" type="xs:boolean" fixed="true"/>
            </xs:sequence>
            <xs:attribute name ="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="medécin">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="citoyen">
                    <xs:complexType>
                        <xs:attribute name="citoyen" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="modification" type="xs:boolean" fixed="true"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="observatoire">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="visibilité" type="xs:boolean" fixed="true"/>
                <xs:element name="modification" type="xs:boolean" fixed="false"/>
            </xs:sequence>
            <xs:attribute name ="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="agence">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="nom" type="xs:string"/>
                    <xs:element name="visibilité" type="xs:boolean" fixed="true"/>
                    <xs:element name="modification" type="xs:boolean" fixed="true"/>
                </xs:sequence>
                <xs:attribute name ="id" type="xs:string"/>
            </xs:complexType>
    </xs:element>

    <xs:element name="antécédent_medical" type="antType"/>
    <xs:complexType name="antType">
        <xs:sequence>
            <xs:element name='consultation' >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='hospitalisation'>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='résultat'>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="négative|positive"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name ="id" type="xs:string"/>
    </xs:complexType>

    <xs:element name="historique_social">
    <xs:complexType>
        <xs:sequence>
            <xs:element name='date' type='xs:date'/>
            <xs:element name='lieu'>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:whiteSpace value="collapse"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name='numInfect' type='xs:nonNegativeInteger'/>
        </xs:sequence>
        <xs:attribute name ="id" type="xs:string"/>
    </xs:complexType>
    </xs:element>

    <xs:element name = "statut" type= "statutType"/>
    <xs:complexType name="statutType">
        <xs:sequence>
            <xs:element name ="infection" type="xs:boolean"/>
            <xs:element name ="immunisation" type="xs:boolean"/>
            <xs:element name ="vaccination" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name ="id" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== keyanfang/BigVir2084/BigVir2084.xml
<?xml version="1.0" encoding="UTF-8"?>
<BigVir2084 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="BigVir2084.xsd">
    <Utilisateur_Personne id="1">
        <type>citoyen</type>
        <nom>Jean</nom>
        <age>18</age>
        <pois>50.5</pois>
        <antécédent_medical antécédent_medical="1"/>
        <historique_social historique_social="2"/>
        <statut statut="3"/>

    </Utilisateur_Personne>

    <Utilisateur_Groupe id="6">
        <type>agence</type>
        <nom>gov</nom>
    </Utilisateur_Groupe>

    <antécédent_medical id="1">
        <consultation>en bonne santé</consultation>
        <hospitalisation>N'ont pas été hospitalisés au cour de la dernière année</hospitalisation>
        <résultat>Negativé</résultat>
    </antécédent_medical>

    <historique_social id="2">
        <date>1998-05-20</date>
        <lieu>Antibes</lieu>
        <numInfect>8</numInfect>
    </historique_social>

    <statut id="3">
        <infection>false</infection>
        <immunisation>false</immunisation>
        <vaccination>false</vaccination>
    </statut>

</BigVir2084>
